server:
  port: 8080
  tomcat:
    basedir: tomcat
web:
  classpath: H:/code/markdown/
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
#    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:~/h2-markdown;SCHEMA=markdowneditor
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.classpath}
logging:
  level:
    root: info
    org.mybatis: debug
    com.guoxiaohei: debug