server:
  port: 8080
  tomcat:
    basedir: tomcat
web:
  classpath: H:/code/markdown/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${user}
    password: ${password}
    #    url: jdbc:h2:~/h2-markdown;SCHEMA=markdowneditor
    url: jdbc:mysql://localhost:3306/markdowneditor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.classpath}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    user:
      name: guoxiaohei
      password: guoxiaohei
logging:
  level:
    root: info
    org.mybatis: debug
    com.guoxiaohei: debug